# Generated by Django 4.2 on 2023-04-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=25)),
                ('production_amount', models.IntegerField(default=0)),
                ('goods_price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['goods_name'],
            },
        ),
        migrations.CreateModel(
            name='Products_in_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('netto', models.IntegerField(default=0)),
                ('projected_gross_profit', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr3A.city')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr3A.good')),
            ],
        ),
    ]
