# Generated by Django 4.2 on 2023-04-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products_in_city',
            options={'ordering': ['city']},
        ),
    ]
