# Generated by Django 4.2 on 2023-04-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0002_alter_products_in_city_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_in_city',
            old_name='netto',
            new_name='tara',
        ),
    ]
