# Generated by Django 4.2 on 2023-04-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0004_rename_projected_gross_profit_products_in_city_netto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
