# Generated by Django 4.2 on 2023-04-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0007_alter_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
