# Generated by Django 4.2 on 2023-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0008_alter_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_in_city',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
