# Generated by Django 4.2 on 2023-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0009_alter_products_in_city_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_in_city',
            name='netto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products_in_city',
            name='tara',
            field=models.FloatField(default=0),
        ),
    ]
