# Generated by Django 4.2 on 2023-04-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0010_alter_products_in_city_netto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_in_city',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
