# Generated by Django 4.2 on 2023-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr3A', '0012_alter_products_in_city_netto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_in_city',
            name='tara',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
